### ISSUE TITLE
Rebase on goodtables.io

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-js#14]
# Overview

We have two options of updating this library:
- use https://github.com/frictionlessdata/goodtables-server-py as inspection provider
- add file uploading support to `goodtables.io` and use this service as inspection provider

**Comment by roll** [comment]
@akariv 
@pwalsh 
I've created placeholder for this task. If it will our next thing to do it will be great to have some OS requirements. One important thing - gt.io doesn't support local files - is it OK? Otherwise we need to implement it.

**Comment by pwalsh** [comment]
@roll as we discussed, we'll need a version of the new API that works like goodtables.okfnlabs.org - takes files and urls and returns a result in single request/response cycle.

**Comment by roll** [comment]
@pwalsh So this sync WEB API also has self-value not related to this lib?

**Comment by pwalsh** [comment]
yes: for a simple webform like goodtables.okfnlabs.org and for small files where a consumer does not need to wait for queued job to be processed.

**Comment by pwalsh** [comment]
@roll changed title to use goodtables.io
