### ISSUE TITLE
Integrate templates with the library

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables-js#16]
# Description

We have good tables reports in several templates in different codebase. It will be nice to centralise the templates and provide them as part of the library.

## Dependent services

- [OS Packager](https://github.com/openspending/os-packager)
- [GoodTables Web](https://github.com/frictionlessdata/goodtables-web)
- [DataPackagist](https://github.com/frictionlessdata/datapackagist)

# Tasks

- [ ] `contrib` or `bindings` module to import + render templates
  - [ ] Angular 1 first so we can ship for OS, and others can be based on the pattern
  - We have an example of similar template binding approach in [babbage.ui](https://github.com/openspending/babbage.ui/tree/master/src/bindings)

**Comment by pwalsh** [comment]
Also https://github.com/openspending/openspending/issues/1180

**Comment by roll** [comment]
MOVED to leading repo
https://github.com/frictionlessdata/goodtables.io/issues/150

**Comment by pwalsh** [comment]
?

**Comment by roll** [comment]
@pwalsh 
Report rendering components is not a part of this repo. 
We better track it as a part of `goodtables.io` issues for now - https://github.com/frictionlessdata/goodtables.io/issues/150 (esp. because in current situation it's totally hidden from @amercader)

**Comment by pwalsh** [comment]
but I am confused - the idea was to ship them as part of this repo.

**Comment by roll** [comment]
@pwalsh 
I had to separate it (based on modern UI component shipping approach). 

But let's discuss it a little bit later (when I'll be finishing it for goodtables.io). I still have some doubts of our approach (with shipping different versions per framework). I have an idea how to radically simplify things but have to discuss with you, @amercader and @akariv.
