### ISSUE TITLE
Consider CliClient implementation

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-js#19]
# Overview

At some point in the future it could be useful to provide `CliClient` and `validate` mode to use local `goodtables` binary. It will solve `don't want my data leave the house` problem using local validation. For now we have implemented only `ApiClient` which use `goodtables.io` cloud service. The `CliClient` should be trivial to develop but it requires https://github.com/frictionlessdata/goodtables-py/issues/175.

**Comment by Stephen-Gates** [comment]
This would be useful. A javascript implementation would be ideal for embedding into an Electron app (i.e. [Data Curator](https://github.com/ODIQueensland/data-curator))
