### ISSUE TITLE
Unable to use goodtables-js: Error Can't create a job on API.

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/goodtables-js#23]
I'm having issues validating a CSV file with the library. Here's a demo I created to show the bug.

https://repl.it/@lauragift21/goodtables-js

The error returned is related to the Job API `UnhandledPromiseRejectionWarning: Error: Can't create a job on API. Reason: "Error: Request failed with status code 403"`

---
Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @lauragift21 

Here are some working credentials (the error 403 was for forbidden):

```
    apiUrl: "https://goodtables.io/api",
    apiToken: "D0123458B8E36326C60253FE4A7FF6662CAB0C48",
    apiSourceId: "9b6b6391-5404-4e7f-bdb8-271c2cb42fbb"

```

The fact that you need to use credentials like this for a public library is not great. But it's how it works atm

**Comment by lauragift21** [comment]
Alright thanks @roll

**Comment by roll** [comment]
@lauragift21 
I've added these credentials as defaults - it's now can be run just as `goodtables.validate(source)` - btw using shared/default credentials is only for public use. It's better to register at `goodtables.io` and get own credentials (as a recommendation for users)

**Comment by lauragift21** [comment]
Great thanks! @roll
